### ISSUE TITLE
run => install

### ISSUE THREAD

**Issue by jujes** [jonnitto/Jonnitto.PhotoSwipe#1]
Hi, some one can tell me how run or install it in Neos?
I use docker...

thanks in advance

**Comment by jonnitto** [comment]
**I know, I've to write a documentation. I'm working on it**

First, run `composer require jonnitto/photoswipe`
It is good to add this package also as a dependency to you site package, so that you can override the [Settings.yaml](../blob/master/Configuration/Settings.yaml)

If you add the mixin to `Jonnitto.PhotoSwipe:LightboxMixin` to a NodeType you'll get the lightbox attribute. Take a look at [Jonnitto.Picture](https://github.com/jonnitto/Jonnitto.Picture) or [Jonnitto.Image](https://github.com/jonnitto/Jonnitto.Image) to see how the Markup is generated. If you use one (or both) NodeTypes, you'll get PhotoSwipe support right out of the box.
